/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current authenticated user info
         * @description Get current authenticated user info
         */
        get: operations["auth-me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/members/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Withdraw membership (Deactivate account)
         * @description Withdraw membership (Deactivate account)
         */
        delete: operations["withdraw"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login/naver": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login with Naver OAuth
         * @description Login with Naver OAuth
         */
        post: operations["login-naver"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/members/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update member profile nickname
         * @description Update member profile nickname
         */
        put: operations["update-profile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a list of books by their IDs
         * @description Get a list of books by their IDs
         */
        get: operations["get-books-by-idssearch-books"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{bookId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get detailed information of a specific book
         * @description Get detailed information of a specific book
         */
        get: operations["get-book-detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/talks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get talks by member ID
         * @description Get talks by member ID
         */
        get: operations["get-talks-by-member"];
        put?: never;
        /**
         * Create a new talk
         * @description Create a new talk
         */
        post: operations["create-talk"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/talks/recommended": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get recommended talks
         * @description Get recommended talks
         */
        get: operations["get-recommended-talks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/talks/{talkId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update an existing talk
         * @description Update an existing talk
         */
        put: operations["update-talk"];
        post?: never;
        /**
         * Delete (soft-delete) an existing talk
         * @description Delete (soft-delete) an existing talk
         */
        delete: operations["delete-talk"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reactions/talks/{talkId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add a reaction to a talk
         * @description Add a reaction to a talk
         */
        post: operations["add-reaction"];
        /**
         * Remove a reaction from a talk
         * @description Remove a reaction from a talk
         */
        delete: operations["remove-reaction"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/talks/book/{bookId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get talks by book ID
         * @description Get talks by book ID
         */
        get: operations["get-talks-by-book"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "Member_api-members-me-profile-379648853": {
            /** @description New nickname (2-10 chars, alphanumeric/hangeul) */
            nickname: string;
        };
        "Member_api-auth-login-naver1482244112": {
            /** @description True if user is already registered */
            registered: boolean;
        };
        /** AuthMeResponse */
        Member_AuthMeResponse: {
            /** @description User Role */
            role?: string | null;
            /** @description User Nickname */
            nickname?: string | null;
            /** @description Login status */
            isLoggedIn: boolean;
            /** @description User ID */
            id?: string | null;
        };
        "Member_api-auth-login-naver1525051994": {
            /** @description OAuth authorization code */
            code: string;
            /** @description OAuth state parameter */
            state: string;
        };
        /** BookListResponse */
        Book_BookListResponse: {
            /** @description Current page number */
            number: number;
            "[]"?: {
                /** @description Thumbnail Image URL (optional) */
                thumbnailImageUrl?: string | null;
                /** @description Author (optional) */
                author?: string | null;
                /** @description Book ISBN */
                isbn: string;
                /** @description Description (optional) */
                description?: string | null;
                /** @description Book ID */
                id: string;
                /** @description External Link URL (optional) */
                externalLinkUrl?: string | null;
                /** @description Book Title */
                title: string;
            };
            /** @description Number of elements in current page */
            numberOfElements: number;
            /** @description Page size */
            size: number;
            /** @description Is last page */
            last: boolean;
            /** @description Pageable info */
            pageable: string;
            sort?: {
                /** @description Sort unsorted */
                unsorted: boolean;
                /** @description Sort sorted */
                sorted: boolean;
                /** @description Sort empty */
                empty: boolean;
            };
            /** @description Is first page */
            first: boolean;
            content?: {
                /** @description Thumbnail Image URL */
                thumbnailImageUrl?: string | null;
                /** @description Author */
                author?: string | null;
                /** @description Book ISBN */
                isbn: string;
                /** @description Description */
                description?: string | null;
                /** @description Book ID */
                id: string;
                /** @description External Link URL */
                externalLinkUrl?: string | null;
                /** @description Book Title */
                title: string;
            }[];
            /** @description Is empty */
            empty: boolean;
        };
        /** BookResponse */
        Book_BookResponse: {
            /** @description Thumbnail Image URL (optional) */
            thumbnailImageUrl?: string | null;
            /** @description Author (optional) */
            author?: string | null;
            /** @description Book ISBN */
            isbn: string;
            /** @description Description (optional) */
            description?: string | null;
            /** @description Book ID */
            id: string;
            /** @description External Link URL (optional) */
            externalLinkUrl?: string | null;
            /** @description Book Title */
            title: string;
        };
        "Talk_api-talks2030240450": {
            /** @description Date when talk becomes hidden (optional, defaults to 1 year) */
            dateToHidden?: string | null;
            /** @description Talk content */
            content: string;
            /** @description Book ID */
            bookId: string;
        };
        "Talk_api-reactions-talks-talkId1159801027": {
            /** @description Reaction type (LIKE, SUPPORT) */
            type: string;
        };
        /** TalkListResponse */
        Talk_TalkListResponse: {
            /** @description Did I Like */
            didILike: boolean;
            /** @description Created At */
            createdAt: string;
            /** @description Is Modified */
            isModified: boolean;
            /** @description Did I Support */
            didISupport: boolean;
            /** @description Support Count */
            supportCount: number;
            /** @description Nickname */
            nickname: string;
            /** @description Like Count */
            likeCount: number;
            /** @description Talk ID */
            id: string;
            /** @description Content */
            content: string;
            /** @description Member ID */
            memberId: string;
            /** @description Book ID */
            bookId: string;
        }[];
        "Talk_api-talks-talkId-349859363": {
            /** @description Updated talk content */
            content: string;
        };
        /** TalkPageResponse */
        Talk_TalkPageResponse: {
            page?: {
                /** @description Current page number */
                number: number;
                /** @description Page size */
                size: number;
                /** @description Total pages */
                totalPages: number;
                /** @description Total elements */
                totalElements: number;
            };
            content?: {
                /** @description Did I Like */
                didILike: boolean;
                /** @description Created At */
                createdAt: string;
                /** @description Is Modified */
                isModified: boolean;
                /** @description Did I Support */
                didISupport: boolean;
                /** @description Support Count */
                supportCount: number;
                /** @description Nickname */
                nickname: string;
                /** @description Like Count */
                likeCount: number;
                /** @description Talk ID */
                id: string;
                /** @description Content */
                content: string;
                /** @description Member ID */
                memberId: string;
                /** @description Book ID */
                bookId: string;
            }[];
        };
        "Talk_api-talks486549215": Record<string, never>;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "auth-me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Member_AuthMeResponse"];
                };
            };
        };
    };
    withdraw: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 204 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "login-naver": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json;charset=UTF-8": components["schemas"]["Member_api-auth-login-naver1525051994"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Member_api-auth-login-naver1482244112"];
                };
            };
        };
    };
    "update-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json;charset=UTF-8": components["schemas"]["Member_api-members-me-profile-379648853"];
            };
        };
        responses: {
            /** @description 204 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "get-books-by-idssearch-books": {
        parameters: {
            query: {
                /** @description Comma-separated list of book IDs */
                id: string;
                /** @description The search keyword */
                keyword: string;
                /** @description Page number (starts from 0) */
                page?: string;
                /** @description Page size */
                size?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Book_BookListResponse"];
                };
            };
        };
    };
    "get-book-detail": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The unique identifier of the book */
                bookId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Book_BookResponse"];
                };
            };
        };
    };
    "get-talks-by-member": {
        parameters: {
            query: {
                /** @description The unique identifier of the member */
                memberId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Talk_TalkPageResponse"];
                };
            };
            /** @description 403 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "create-talk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json;charset=UTF-8": components["schemas"]["Talk_api-talks2030240450"];
            };
        };
        responses: {
            /** @description 201 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Talk_api-talks486549215"];
                };
            };
        };
    };
    "get-recommended-talks": {
        parameters: {
            query?: {
                /** @description Number of talks to return (default: 5) */
                size?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Talk_TalkListResponse"];
                };
            };
        };
    };
    "update-talk": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Talk ID */
                talkId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json;charset=UTF-8": components["schemas"]["Talk_api-talks-talkId-349859363"];
            };
        };
        responses: {
            /** @description 204 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "delete-talk": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Talk ID */
                talkId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 204 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "add-reaction": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Talk ID */
                talkId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json;charset=UTF-8": components["schemas"]["Talk_api-reactions-talks-talkId1159801027"];
            };
        };
        responses: {
            /** @description 204 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "remove-reaction": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Talk ID */
                talkId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json;charset=UTF-8": components["schemas"]["Talk_api-reactions-talks-talkId1159801027"];
            };
        };
        responses: {
            /** @description 204 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "get-talks-by-book": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The unique identifier of the book */
                bookId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Talk_TalkPageResponse"];
                };
            };
        };
    };
}
